# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ADD_NEW_REALM.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ADD_NEW_REALM(object):
    def setupUi(self, ADD_NEW_REALM):
        ADD_NEW_REALM.setObjectName("ADD_NEW_REALM")
        ADD_NEW_REALM.resize(1386, 1021)
        ADD_NEW_REALM.setToolTip("")
        ADD_NEW_REALM.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.centralwidget = QtWidgets.QWidget(ADD_NEW_REALM)
        self.centralwidget.setObjectName("centralwidget")
        self.OP = QtWidgets.QLineEdit(self.centralwidget)
        self.OP.setGeometry(QtCore.QRect(190, 10, 371, 21))
        self.OP.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.OP.setObjectName("OP")
        self.OP_SELECT = QtWidgets.QComboBox(self.centralwidget)
        self.OP_SELECT.setGeometry(QtCore.QRect(190, 40, 371, 21))
        self.OP_SELECT.setObjectName("OP_SELECT")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(70, 190, 1271, 441))
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tableWidget.setRowCount(1000)
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(5)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.OP_LIST = QtWidgets.QLineEdit(self.centralwidget)
        self.OP_LIST.setGeometry(QtCore.QRect(190, 70, 371, 21))
        self.OP_LIST.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.OP_LIST.setText("")
        self.OP_LIST.setObjectName("OP_LIST")
        self.PROVISION = QtWidgets.QPushButton(self.centralwidget)
        self.PROVISION.setGeometry(QtCore.QRect(70, 640, 75, 23))
        self.PROVISION.setObjectName("PROVISION")
        self.EMAIL = QtWidgets.QPushButton(self.centralwidget)
        self.EMAIL.setGeometry(QtCore.QRect(500, 640, 191, 23))
        self.EMAIL.setObjectName("EMAIL")
        self.RE_AP_LIST = QtWidgets.QPushButton(self.centralwidget)
        self.RE_AP_LIST.setGeometry(QtCore.QRect(180, 640, 75, 23))
        self.RE_AP_LIST.setObjectName("RE_AP_LIST")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.BUILD = QtWidgets.QPushButton(self.centralwidget)
        self.BUILD.setGeometry(QtCore.QRect(70, 160, 181, 23))
        self.BUILD.setObjectName("BUILD")
        self.REALMS = QtWidgets.QLineEdit(self.centralwidget)
        self.REALMS.setGeometry(QtCore.QRect(190, 100, 371, 21))
        self.REALMS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.REALMS.setText("")
        self.REALMS.setObjectName("REALMS")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.NEW_REALMS = QtWidgets.QLineEdit(self.centralwidget)
        self.NEW_REALMS.setGeometry(QtCore.QRect(190, 130, 371, 21))
        self.NEW_REALMS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NEW_REALMS.setText("")
        self.NEW_REALMS.setObjectName("NEW_REALMS")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 130, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(640, 10, 401, 141))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.RE_EU_LIST = QtWidgets.QPushButton(self.centralwidget)
        self.RE_EU_LIST.setGeometry(QtCore.QRect(280, 640, 75, 23))
        self.RE_EU_LIST.setObjectName("RE_EU_LIST")
        self.RE_NA_LIST = QtWidgets.QPushButton(self.centralwidget)
        self.RE_NA_LIST.setGeometry(QtCore.QRect(380, 640, 75, 23))
        self.RE_NA_LIST.setObjectName("RE_NA_LIST")
        self.OP_SELECT.raise_()
        self.OP.raise_()
        self.tableWidget.raise_()
        self.OP_LIST.raise_()
        self.PROVISION.raise_()
        self.EMAIL.raise_()
        self.RE_AP_LIST.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.BUILD.raise_()
        self.REALMS.raise_()
        self.label_4.raise_()
        self.NEW_REALMS.raise_()
        self.label_5.raise_()
        self.textEdit.raise_()
        self.RE_EU_LIST.raise_()
        self.RE_NA_LIST.raise_()
        ADD_NEW_REALM.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ADD_NEW_REALM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1386, 21))
        self.menubar.setObjectName("menubar")
        ADD_NEW_REALM.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ADD_NEW_REALM)
        self.statusbar.setObjectName("statusbar")
        ADD_NEW_REALM.setStatusBar(self.statusbar)

        self.retranslateUi(ADD_NEW_REALM)
        QtCore.QMetaObject.connectSlotsByName(ADD_NEW_REALM)

    def retranslateUi(self, ADD_NEW_REALM):
        _translate = QtCore.QCoreApplication.translate
        ADD_NEW_REALM.setWindowTitle(_translate("ADD_NEW_REALM", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ADD_NEW_REALM", "Roaming Partner"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ADD_NEW_REALM", "RP connection"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ADD_NEW_REALM", "RP LISTCACHE"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ADD_NEW_REALM", "Region1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ADD_NEW_REALM", "Region2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("ADD_NEW_REALM", "Region3"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("ADD_NEW_REALM", "R1-DSC1"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("ADD_NEW_REALM", "R1-DSC2"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("ADD_NEW_REALM", "R2-DSC1"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("ADD_NEW_REALM", "R2-DSC2"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("ADD_NEW_REALM", "R3-DSC1"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("ADD_NEW_REALM", "R3-DSC2"))
        self.PROVISION.setText(_translate("ADD_NEW_REALM", "Provision"))
        self.EMAIL.setText(_translate("ADD_NEW_REALM", "Email(Only after provison)"))
        self.RE_AP_LIST.setText(_translate("ADD_NEW_REALM", "Re_AP_LIST"))
        self.label.setText(_translate("ADD_NEW_REALM", "Input OP Name"))
        self.label_2.setText(_translate("ADD_NEW_REALM", "Select OP"))
        self.label_3.setText(_translate("ADD_NEW_REALM", "LISTCACHE of OP"))
        self.BUILD.setText(_translate("ADD_NEW_REALM", "Edit RMT Route(Please Click Twice)"))
        self.label_4.setText(_translate("ADD_NEW_REALM", "Realms"))
        self.label_5.setText(_translate("ADD_NEW_REALM", "Input new realms"))
        self.textEdit.setHtml(_translate("ADD_NEW_REALM", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">For Operator which add new realm, please do follow procedure before using this table:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.Process step 1 in OP online(For CCB part, DRACustomerRealmName is to be updated),you can remove all histrical realm showed in step 5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.Process step 2,3,4,5,8,9,10,11,12</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3.Click Edit RMT Route twice then proceed.</p></body></html>"))
        self.RE_EU_LIST.setText(_translate("ADD_NEW_REALM", "Re_EU_LIST"))
        self.RE_NA_LIST.setText(_translate("ADD_NEW_REALM", "Re_NA_LIST"))

