# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MASSIVE_RULE.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MASSIVE_RULE(object):
    def setupUi(self, MASSIVE_RULE):
        MASSIVE_RULE.setObjectName("MASSIVE_RULE")
        MASSIVE_RULE.resize(1333, 692)
        self.centralwidget = QtWidgets.QWidget(MASSIVE_RULE)
        self.centralwidget.setObjectName("centralwidget")
        self.ComboBox_DSC = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox_DSC.setGeometry(QtCore.QRect(60, 30, 151, 21))
        self.ComboBox_DSC.setObjectName("ComboBox_DSC")
        self.DUMP_RULE = QtWidgets.QPushButton(self.centralwidget)
        self.DUMP_RULE.setGeometry(QtCore.QRect(60, 80, 151, 23))
        self.DUMP_RULE.setObjectName("DUMP_RULE")
        self.OPEN_RULE = QtWidgets.QPushButton(self.centralwidget)
        self.OPEN_RULE.setGeometry(QtCore.QRect(60, 110, 151, 23))
        self.OPEN_RULE.setObjectName("OPEN_RULE")
        self.EXECUTE_ALL_RULE = QtWidgets.QPushButton(self.centralwidget)
        self.EXECUTE_ALL_RULE.setGeometry(QtCore.QRect(60, 400, 151, 23))
        self.EXECUTE_ALL_RULE.setObjectName("EXECUTE_ALL_RULE")
        self.adjacentSourcePeerName = QtWidgets.QLineEdit(self.centralwidget)
        self.adjacentSourcePeerName.setGeometry(QtCore.QRect(410, 230, 431, 20))
        self.adjacentSourcePeerName.setObjectName("adjacentSourcePeerName")
        self.condition = QtWidgets.QTextEdit(self.centralwidget)
        self.condition.setGeometry(QtCore.QRect(410, 440, 431, 71))
        self.condition.setObjectName("condition")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 230, 141, 21))
        self.label.setObjectName("label")
        self.adjacentSourceRealmName = QtWidgets.QLineEdit(self.centralwidget)
        self.adjacentSourceRealmName.setGeometry(QtCore.QRect(410, 260, 431, 20))
        self.adjacentSourceRealmName.setObjectName("adjacentSourceRealmName")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 260, 131, 21))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(660, 200, 61, 21))
        self.label_4.setObjectName("label_4")
        self.appId = QtWidgets.QLineEdit(self.centralwidget)
        self.appId.setGeometry(QtCore.QRect(700, 200, 141, 20))
        self.appId.setText("")
        self.appId.setObjectName("appId")
        self.srcHost = QtWidgets.QLineEdit(self.centralwidget)
        self.srcHost.setGeometry(QtCore.QRect(410, 320, 431, 20))
        self.srcHost.setText("")
        self.srcHost.setObjectName("srcHost")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 320, 131, 21))
        self.label_5.setObjectName("label_5")
        self.srcRealm = QtWidgets.QLineEdit(self.centralwidget)
        self.srcRealm.setGeometry(QtCore.QRect(410, 350, 431, 20))
        self.srcRealm.setText("")
        self.srcRealm.setObjectName("srcRealm")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(270, 350, 131, 21))
        self.label_6.setObjectName("label_6")
        self.destHost = QtWidgets.QLineEdit(self.centralwidget)
        self.destHost.setGeometry(QtCore.QRect(410, 380, 431, 20))
        self.destHost.setText("")
        self.destHost.setObjectName("destHost")
        self.destRealm = QtWidgets.QLineEdit(self.centralwidget)
        self.destRealm.setGeometry(QtCore.QRect(410, 410, 431, 20))
        self.destRealm.setText("")
        self.destRealm.setObjectName("destRealm")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(270, 380, 131, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(270, 410, 131, 21))
        self.label_8.setObjectName("label_8")
        self.priority = QtWidgets.QLineEdit(self.centralwidget)
        self.priority.setGeometry(QtCore.QRect(640, 290, 31, 20))
        self.priority.setText("")
        self.priority.setObjectName("priority")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(600, 290, 41, 21))
        self.label_9.setObjectName("label_9")
        self.ruleType = QtWidgets.QLineEdit(self.centralwidget)
        self.ruleType.setGeometry(QtCore.QRect(410, 290, 181, 20))
        self.ruleType.setText("")
        self.ruleType.setObjectName("ruleType")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(270, 290, 131, 21))
        self.label_10.setObjectName("label_10")
        self.id = QtWidgets.QLineEdit(self.centralwidget)
        self.id.setGeometry(QtCore.QRect(410, 200, 131, 20))
        self.id.setText("")
        self.id.setObjectName("id")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(270, 200, 131, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(270, 440, 131, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(270, 520, 131, 21))
        self.label_13.setObjectName("label_13")
        self.consequence = QtWidgets.QTextEdit(self.centralwidget)
        self.consequence.setGeometry(QtCore.QRect(410, 520, 431, 41))
        self.consequence.setObjectName("consequence")
        self.label_dscRuleGroup = QtWidgets.QLabel(self.centralwidget)
        self.label_dscRuleGroup.setGeometry(QtCore.QRect(680, 290, 71, 21))
        self.label_dscRuleGroup.setObjectName("label_dscRuleGroup")
        self.dscRuleGroup = QtWidgets.QLineEdit(self.centralwidget)
        self.dscRuleGroup.setGeometry(QtCore.QRect(750, 290, 91, 20))
        self.dscRuleGroup.setText("")
        self.dscRuleGroup.setObjectName("dscRuleGroup")
        self.description = QtWidgets.QTextEdit(self.centralwidget)
        self.description.setGeometry(QtCore.QRect(410, 570, 431, 71))
        self.description.setObjectName("description")
        self.lable_description = QtWidgets.QLabel(self.centralwidget)
        self.lable_description.setGeometry(QtCore.QRect(270, 570, 131, 21))
        self.lable_description.setObjectName("lable_description")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(270, 170, 131, 21))
        self.label_16.setObjectName("label_16")
        self.CURRENT_RULE_FILE = QtWidgets.QLineEdit(self.centralwidget)
        self.CURRENT_RULE_FILE.setGeometry(QtCore.QRect(570, 170, 271, 20))
        self.CURRENT_RULE_FILE.setText("")
        self.CURRENT_RULE_FILE.setObjectName("CURRENT_RULE_FILE")
        self.ComboBox_RULE_INDEX = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox_RULE_INDEX.setGeometry(QtCore.QRect(60, 160, 151, 21))
        self.ComboBox_RULE_INDEX.setObjectName("ComboBox_RULE_INDEX")
        self.EXECUTE_CURRENT_RULE = QtWidgets.QPushButton(self.centralwidget)
        self.EXECUTE_CURRENT_RULE.setGeometry(QtCore.QRect(60, 350, 151, 23))
        self.EXECUTE_CURRENT_RULE.setObjectName("EXECUTE_CURRENT_RULE")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(60, 10, 131, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(60, 60, 131, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(60, 140, 131, 21))
        self.label_19.setObjectName("label_19")
        self.ComboBox_Funtion = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox_Funtion.setGeometry(QtCore.QRect(380, 50, 151, 21))
        self.ComboBox_Funtion.setObjectName("ComboBox_Funtion")
        self.ComboBox_from_OP = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox_from_OP.setGeometry(QtCore.QRect(720, 50, 151, 21))
        self.ComboBox_from_OP.setObjectName("ComboBox_from_OP")
        self.ComboBox_to_OP = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox_to_OP.setGeometry(QtCore.QRect(890, 50, 151, 21))
        self.ComboBox_to_OP.setObjectName("ComboBox_to_OP")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(380, 30, 831, 21))
        self.label_20.setObjectName("label_20")
        self.ComboBox_Main_OP = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox_Main_OP.setGeometry(QtCore.QRect(550, 50, 151, 21))
        self.ComboBox_Main_OP.setObjectName("ComboBox_Main_OP")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(380, 10, 841, 21))
        self.label_21.setObjectName("label_21")
        self.FILTER_RULE = QtWidgets.QPushButton(self.centralwidget)
        self.FILTER_RULE.setGeometry(QtCore.QRect(60, 190, 151, 23))
        self.FILTER_RULE.setObjectName("FILTER_RULE")
        self.ACTION = QtWidgets.QLineEdit(self.centralwidget)
        self.ACTION.setGeometry(QtCore.QRect(1060, 50, 131, 20))
        self.ACTION.setText("")
        self.ACTION.setObjectName("ACTION")
        self.ComboBox_FILTERED_RULE_INDEX = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox_FILTERED_RULE_INDEX.setGeometry(QtCore.QRect(60, 240, 151, 21))
        self.ComboBox_FILTERED_RULE_INDEX.setObjectName("ComboBox_FILTERED_RULE_INDEX")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(60, 220, 131, 21))
        self.label_22.setObjectName("label_22")
        self.DESC_CONTAINS = QtWidgets.QLineEdit(self.centralwidget)
        self.DESC_CONTAINS.setGeometry(QtCore.QRect(380, 120, 221, 20))
        self.DESC_CONTAINS.setText("")
        self.DESC_CONTAINS.setObjectName("DESC_CONTAINS")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(380, 100, 191, 21))
        self.label_14.setObjectName("label_14")
        self.MAIN_SSID = QtWidgets.QLineEdit(self.centralwidget)
        self.MAIN_SSID.setGeometry(QtCore.QRect(550, 80, 151, 20))
        self.MAIN_SSID.setText("")
        self.MAIN_SSID.setObjectName("MAIN_SSID")
        self.FROM_SSID = QtWidgets.QLineEdit(self.centralwidget)
        self.FROM_SSID.setGeometry(QtCore.QRect(720, 80, 151, 20))
        self.FROM_SSID.setText("")
        self.FROM_SSID.setObjectName("FROM_SSID")
        self.TO_SSID = QtWidgets.QLineEdit(self.centralwidget)
        self.TO_SSID.setGeometry(QtCore.QRect(890, 80, 151, 20))
        self.TO_SSID.setText("")
        self.TO_SSID.setObjectName("TO_SSID")
        self.Standard_RuleType = QtWidgets.QComboBox(self.centralwidget)
        self.Standard_RuleType.setGeometry(QtCore.QRect(910, 180, 271, 21))
        self.Standard_RuleType.setObjectName("Standard_RuleType")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(910, 150, 131, 21))
        self.label_23.setObjectName("label_23")
        self.COND_CONTAINS = QtWidgets.QLineEdit(self.centralwidget)
        self.COND_CONTAINS.setGeometry(QtCore.QRect(620, 120, 251, 20))
        self.COND_CONTAINS.setText("")
        self.COND_CONTAINS.setObjectName("COND_CONTAINS")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(620, 100, 191, 21))
        self.label_15.setObjectName("label_15")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(510, 170, 81, 21))
        self.label_24.setObjectName("label_24")
        self.dsc = QtWidgets.QLineEdit(self.centralwidget)
        self.dsc.setGeometry(QtCore.QRect(410, 170, 81, 20))
        self.dsc.setText("")
        self.dsc.setObjectName("dsc")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(60, 330, 151, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(60, 380, 151, 21))
        self.label_26.setObjectName("label_26")
        self.MODIFY_CURRENT_RULE = QtWidgets.QPushButton(self.centralwidget)
        self.MODIFY_CURRENT_RULE.setGeometry(QtCore.QRect(60, 460, 151, 23))
        self.MODIFY_CURRENT_RULE.setObjectName("MODIFY_CURRENT_RULE")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(60, 440, 151, 21))
        self.label_27.setObjectName("label_27")
        self.MODIFY_ALL_RULE = QtWidgets.QPushButton(self.centralwidget)
        self.MODIFY_ALL_RULE.setGeometry(QtCore.QRect(60, 520, 151, 23))
        self.MODIFY_ALL_RULE.setObjectName("MODIFY_ALL_RULE")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(60, 500, 151, 21))
        self.label_28.setObjectName("label_28")
        self.SAVE_FILTERED_RULE = QtWidgets.QPushButton(self.centralwidget)
        self.SAVE_FILTERED_RULE.setGeometry(QtCore.QRect(60, 270, 151, 23))
        self.SAVE_FILTERED_RULE.setObjectName("SAVE_FILTERED_RULE")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(270, 30, 131, 21))
        self.label_29.setObjectName("label_29")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 10, 851, 141))
        self.label_3.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(890, 100, 191, 21))
        self.label_30.setObjectName("label_30")
        self.CONS_CONTAINS = QtWidgets.QLineEdit(self.centralwidget)
        self.CONS_CONTAINS.setGeometry(QtCore.QRect(890, 120, 301, 20))
        self.CONS_CONTAINS.setText("")
        self.CONS_CONTAINS.setObjectName("CONS_CONTAINS")
        self.label_3.raise_()
        self.ComboBox_DSC.raise_()
        self.DUMP_RULE.raise_()
        self.OPEN_RULE.raise_()
        self.EXECUTE_ALL_RULE.raise_()
        self.adjacentSourcePeerName.raise_()
        self.condition.raise_()
        self.label.raise_()
        self.adjacentSourceRealmName.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.appId.raise_()
        self.srcHost.raise_()
        self.label_5.raise_()
        self.srcRealm.raise_()
        self.label_6.raise_()
        self.destHost.raise_()
        self.destRealm.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.priority.raise_()
        self.label_9.raise_()
        self.ruleType.raise_()
        self.label_10.raise_()
        self.id.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.consequence.raise_()
        self.label_dscRuleGroup.raise_()
        self.dscRuleGroup.raise_()
        self.description.raise_()
        self.lable_description.raise_()
        self.label_16.raise_()
        self.CURRENT_RULE_FILE.raise_()
        self.ComboBox_RULE_INDEX.raise_()
        self.EXECUTE_CURRENT_RULE.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.ComboBox_Funtion.raise_()
        self.ComboBox_from_OP.raise_()
        self.ComboBox_to_OP.raise_()
        self.label_20.raise_()
        self.ComboBox_Main_OP.raise_()
        self.label_21.raise_()
        self.FILTER_RULE.raise_()
        self.ACTION.raise_()
        self.ComboBox_FILTERED_RULE_INDEX.raise_()
        self.label_22.raise_()
        self.DESC_CONTAINS.raise_()
        self.label_14.raise_()
        self.MAIN_SSID.raise_()
        self.FROM_SSID.raise_()
        self.TO_SSID.raise_()
        self.Standard_RuleType.raise_()
        self.label_23.raise_()
        self.COND_CONTAINS.raise_()
        self.label_15.raise_()
        self.label_24.raise_()
        self.dsc.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.MODIFY_CURRENT_RULE.raise_()
        self.label_27.raise_()
        self.MODIFY_ALL_RULE.raise_()
        self.label_28.raise_()
        self.SAVE_FILTERED_RULE.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.CONS_CONTAINS.raise_()
        MASSIVE_RULE.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MASSIVE_RULE)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1333, 21))
        self.menubar.setObjectName("menubar")
        MASSIVE_RULE.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MASSIVE_RULE)
        self.statusbar.setObjectName("statusbar")
        MASSIVE_RULE.setStatusBar(self.statusbar)

        self.retranslateUi(MASSIVE_RULE)
        QtCore.QMetaObject.connectSlotsByName(MASSIVE_RULE)

    def retranslateUi(self, MASSIVE_RULE):
        _translate = QtCore.QCoreApplication.translate
        MASSIVE_RULE.setWindowTitle(_translate("MASSIVE_RULE", "MainWindow"))
        self.DUMP_RULE.setText(_translate("MASSIVE_RULE", "Dump Rule"))
        self.OPEN_RULE.setText(_translate("MASSIVE_RULE", "Open Rule File"))
        self.EXECUTE_ALL_RULE.setText(_translate("MASSIVE_RULE", "Execute All Rule"))
        self.label.setText(_translate("MASSIVE_RULE", "adjacentSourcePeerName"))
        self.label_2.setText(_translate("MASSIVE_RULE", "adjacentSourceRealmName"))
        self.label_4.setText(_translate("MASSIVE_RULE", "appId"))
        self.label_5.setText(_translate("MASSIVE_RULE", "srcHost"))
        self.label_6.setText(_translate("MASSIVE_RULE", "srcRealm"))
        self.label_7.setText(_translate("MASSIVE_RULE", "destHost"))
        self.label_8.setText(_translate("MASSIVE_RULE", "destRealm"))
        self.label_9.setText(_translate("MASSIVE_RULE", "priority"))
        self.label_10.setText(_translate("MASSIVE_RULE", "ruleType"))
        self.label_11.setText(_translate("MASSIVE_RULE", "id"))
        self.label_12.setText(_translate("MASSIVE_RULE", "condition"))
        self.label_13.setText(_translate("MASSIVE_RULE", "consequence"))
        self.label_dscRuleGroup.setText(_translate("MASSIVE_RULE", "dscRuleGroup"))
        self.lable_description.setText(_translate("MASSIVE_RULE", "description"))
        self.label_16.setText(_translate("MASSIVE_RULE", "Current DSC"))
        self.EXECUTE_CURRENT_RULE.setText(_translate("MASSIVE_RULE", "Execute Current Rule"))
        self.label_17.setText(_translate("MASSIVE_RULE", "Select DSC"))
        self.label_18.setText(_translate("MASSIVE_RULE", "Function"))
        self.label_19.setText(_translate("MASSIVE_RULE", "Index of all rules"))
        self.label_20.setText(_translate("MASSIVE_RULE", "BLOCK_OB_TRAFFIC                      %Vodafone_Qatar_Q_S_C 6761% from T-Mobile_USA_Inc 6648          % to Vodafone_Qatar_Q_S_C 6761% Reject with3002"))
        self.label_21.setText(_translate("MASSIVE_RULE", "Function(starts with)                      %Operator  name ssid                % from Operator Name ssid                  % to Perator Name SSID                  %Action contains"))
        self.FILTER_RULE.setText(_translate("MASSIVE_RULE", "Filter Rule"))
        self.label_22.setText(_translate("MASSIVE_RULE", "Index of filtered rules"))
        self.label_14.setText(_translate("MASSIVE_RULE", "Description Contains"))
        self.label_23.setText(_translate("MASSIVE_RULE", "Standard RuleType"))
        self.label_15.setText(_translate("MASSIVE_RULE", "Condtion Contains"))
        self.label_24.setText(_translate("MASSIVE_RULE", "Current File"))
        self.label_25.setText(_translate("MASSIVE_RULE", "DSC & dscRuleGroup ignored"))
        self.label_26.setText(_translate("MASSIVE_RULE", "DSC & dscRuleGroup ignored"))
        self.MODIFY_CURRENT_RULE.setText(_translate("MASSIVE_RULE", "Modify Current Rule"))
        self.label_27.setText(_translate("MASSIVE_RULE", "dscRuleGroup ignored"))
        self.MODIFY_ALL_RULE.setText(_translate("MASSIVE_RULE", "Modify All Rules"))
        self.label_28.setText(_translate("MASSIVE_RULE", "dscRuleGroup ignored"))
        self.SAVE_FILTERED_RULE.setText(_translate("MASSIVE_RULE", "Save Filtered Rule"))
        self.label_29.setText(_translate("MASSIVE_RULE", "Filters"))
        self.label_30.setText(_translate("MASSIVE_RULE", "Consequence Contains"))

