# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_OPEN_ROUTE.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Ui_OPEN_ROUTE_WIN(object):
    def setupUi(self, Ui_OPEN_ROUTE_WIN):
        Ui_OPEN_ROUTE_WIN.setObjectName("Ui_OPEN_ROUTE_WIN")
        Ui_OPEN_ROUTE_WIN.resize(1352, 696)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ooopic_1526549922.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_OPEN_ROUTE_WIN.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Ui_OPEN_ROUTE_WIN)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 170, 47, 13))
        self.label.setObjectName("label")
        self.SSID_A = QtWidgets.QLineEdit(self.centralwidget)
        self.SSID_A.setGeometry(QtCore.QRect(110, 170, 171, 20))
        self.SSID_A.setObjectName("SSID_A")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_3.setObjectName("label_3")
        self.OP_A = QtWidgets.QLineEdit(self.centralwidget)
        self.OP_A.setGeometry(QtCore.QRect(110, 50, 391, 20))
        self.OP_A.setObjectName("OP_A")
        self.Combo_Select_A = QtWidgets.QComboBox(self.centralwidget)
        self.Combo_Select_A.setGeometry(QtCore.QRect(110, 80, 391, 21))
        self.Combo_Select_A.setObjectName("Combo_Select_A")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 61, 16))
        self.label_4.setObjectName("label_4")
        self.Country_A = QtWidgets.QLineEdit(self.centralwidget)
        self.Country_A.setGeometry(QtCore.QRect(110, 110, 391, 20))
        self.Country_A.setObjectName("Country_A")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 61, 16))
        self.label_5.setObjectName("label_5")
        self.realm_A = QtWidgets.QLineEdit(self.centralwidget)
        self.realm_A.setGeometry(QtCore.QRect(110, 140, 391, 20))
        self.realm_A.setObjectName("realm_A")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 170, 81, 16))
        self.label_7.setObjectName("label_7")
        self.LISTREGION_A = QtWidgets.QLineEdit(self.centralwidget)
        self.LISTREGION_A.setGeometry(QtCore.QRect(400, 170, 101, 20))
        self.LISTREGION_A.setObjectName("LISTREGION_A")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 200, 61, 16))
        self.label_8.setObjectName("label_8")
        self.LIST_A = QtWidgets.QLineEdit(self.centralwidget)
        self.LIST_A.setGeometry(QtCore.QRect(110, 200, 391, 20))
        self.LIST_A.setObjectName("LIST_A")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 230, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(300, 230, 81, 16))
        self.label_10.setObjectName("label_10")
        self.RMT_A = QtWidgets.QLineEdit(self.centralwidget)
        self.RMT_A.setGeometry(QtCore.QRect(400, 230, 101, 20))
        self.RMT_A.setObjectName("RMT_A")
        self.Owner_A = QtWidgets.QLineEdit(self.centralwidget)
        self.Owner_A.setGeometry(QtCore.QRect(110, 230, 171, 20))
        self.Owner_A.setObjectName("Owner_A")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 260, 61, 16))
        self.label_11.setObjectName("label_11")
        self.DRA_A = QtWidgets.QLineEdit(self.centralwidget)
        self.DRA_A.setGeometry(QtCore.QRect(110, 260, 391, 20))
        self.DRA_A.setText("")
        self.DRA_A.setObjectName("DRA_A")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 290, 61, 16))
        self.label_12.setObjectName("label_12")
        self.HUB_POLICY_A = QtWidgets.QTextEdit(self.centralwidget)
        self.HUB_POLICY_A.setGeometry(QtCore.QRect(110, 290, 391, 111))
        self.HUB_POLICY_A.setObjectName("HUB_POLICY_A")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 410, 101, 16))
        self.label_13.setObjectName("label_13")
        self.TECH_COMMENT_A = QtWidgets.QTextEdit(self.centralwidget)
        self.TECH_COMMENT_A.setGeometry(QtCore.QRect(110, 410, 391, 151))
        self.TECH_COMMENT_A.setObjectName("TECH_COMMENT_A")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 570, 71, 16))
        self.label_14.setObjectName("label_14")
        self.Combo_Region_A = QtWidgets.QComboBox(self.centralwidget)
        self.Combo_Region_A.setGeometry(QtCore.QRect(110, 570, 51, 21))
        self.Combo_Region_A.setObjectName("Combo_Region_A")
        self.B_Reams2A_LIST = QtWidgets.QPushButton(self.centralwidget)
        self.B_Reams2A_LIST.setGeometry(QtCore.QRect(190, 570, 151, 23))
        self.B_Reams2A_LIST.setObjectName("B_Reams2A_LIST")
        self.Check_TO_A_Route = QtWidgets.QPushButton(self.centralwidget)
        self.Check_TO_A_Route.setGeometry(QtCore.QRect(360, 570, 141, 23))
        self.Check_TO_A_Route.setObjectName("Check_TO_A_Route")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(520, 200, 61, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(520, 230, 61, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(530, 570, 71, 16))
        self.label_18.setObjectName("label_18")
        self.realm_B = QtWidgets.QLineEdit(self.centralwidget)
        self.realm_B.setGeometry(QtCore.QRect(620, 140, 391, 20))
        self.realm_B.setObjectName("realm_B")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(810, 20, 47, 13))
        self.label_19.setObjectName("label_19")
        self.Country_B = QtWidgets.QLineEdit(self.centralwidget)
        self.Country_B.setGeometry(QtCore.QRect(620, 110, 391, 20))
        self.Country_B.setObjectName("Country_B")
        self.LISTREGION_B = QtWidgets.QLineEdit(self.centralwidget)
        self.LISTREGION_B.setGeometry(QtCore.QRect(910, 170, 101, 20))
        self.LISTREGION_B.setObjectName("LISTREGION_B")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(520, 290, 61, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(520, 110, 61, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(520, 140, 61, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(520, 20, 61, 16))
        self.label_23.setObjectName("label_23")
        self.Combo_Region_B = QtWidgets.QComboBox(self.centralwidget)
        self.Combo_Region_B.setGeometry(QtCore.QRect(620, 570, 51, 21))
        self.Combo_Region_B.setObjectName("Combo_Region_B")
        self.Check_TO_B_Route = QtWidgets.QPushButton(self.centralwidget)
        self.Check_TO_B_Route.setGeometry(QtCore.QRect(870, 570, 141, 23))
        self.Check_TO_B_Route.setObjectName("Check_TO_B_Route")
        self.SSID_B = QtWidgets.QLineEdit(self.centralwidget)
        self.SSID_B.setGeometry(QtCore.QRect(620, 170, 171, 20))
        self.SSID_B.setObjectName("SSID_B")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(520, 50, 47, 13))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(810, 170, 81, 16))
        self.label_26.setObjectName("label_26")
        self.A_Reams2B_LIST = QtWidgets.QPushButton(self.centralwidget)
        self.A_Reams2B_LIST.setGeometry(QtCore.QRect(700, 570, 151, 23))
        self.A_Reams2B_LIST.setObjectName("A_Reams2B_LIST")
        self.DRA_B = QtWidgets.QLineEdit(self.centralwidget)
        self.DRA_B.setGeometry(QtCore.QRect(620, 260, 391, 20))
        self.DRA_B.setText("")
        self.DRA_B.setObjectName("DRA_B")
        self.Combo_Select_B = QtWidgets.QComboBox(self.centralwidget)
        self.Combo_Select_B.setGeometry(QtCore.QRect(620, 80, 391, 21))
        self.Combo_Select_B.setObjectName("Combo_Select_B")
        self.Owner_B = QtWidgets.QLineEdit(self.centralwidget)
        self.Owner_B.setGeometry(QtCore.QRect(620, 230, 171, 20))
        self.Owner_B.setObjectName("Owner_B")
        self.LIST_B = QtWidgets.QLineEdit(self.centralwidget)
        self.LIST_B.setGeometry(QtCore.QRect(620, 200, 391, 20))
        self.LIST_B.setObjectName("LIST_B")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(520, 170, 47, 13))
        self.label_27.setObjectName("label_27")
        self.RMT_B = QtWidgets.QLineEdit(self.centralwidget)
        self.RMT_B.setGeometry(QtCore.QRect(910, 230, 101, 20))
        self.RMT_B.setObjectName("RMT_B")
        self.OP_B = QtWidgets.QLineEdit(self.centralwidget)
        self.OP_B.setGeometry(QtCore.QRect(620, 50, 391, 20))
        self.OP_B.setObjectName("OP_B")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(520, 260, 61, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(520, 410, 101, 16))
        self.label_29.setObjectName("label_29")
        self.HUB_POLICY_B = QtWidgets.QTextEdit(self.centralwidget)
        self.HUB_POLICY_B.setGeometry(QtCore.QRect(620, 290, 391, 111))
        self.HUB_POLICY_B.setObjectName("HUB_POLICY_B")
        self.TECH_COMMENT_B = QtWidgets.QTextEdit(self.centralwidget)
        self.TECH_COMMENT_B.setGeometry(QtCore.QRect(620, 410, 391, 151))
        self.TECH_COMMENT_B.setObjectName("TECH_COMMENT_B")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(810, 230, 81, 16))
        self.label_30.setObjectName("label_30")
        self.UPD_DB = QtWidgets.QPushButton(self.centralwidget)
        self.UPD_DB.setGeometry(QtCore.QRect(1030, 10, 81, 23))
        self.UPD_DB.setObjectName("UPD_DB")
        self.BKP_DB = QtWidgets.QPushButton(self.centralwidget)
        self.BKP_DB.setGeometry(QtCore.QRect(1130, 10, 81, 23))
        self.BKP_DB.setObjectName("BKP_DB")
        self.RST_DB = QtWidgets.QPushButton(self.centralwidget)
        self.RST_DB.setGeometry(QtCore.QRect(1220, 10, 81, 23))
        self.RST_DB.setObjectName("RST_DB")
        self.Re_AP_LIST = QtWidgets.QPushButton(self.centralwidget)
        self.Re_AP_LIST.setGeometry(QtCore.QRect(1030, 190, 81, 23))
        self.Re_AP_LIST.setObjectName("Re_AP_LIST")
        self.Re_EU_LIST = QtWidgets.QPushButton(self.centralwidget)
        self.Re_EU_LIST.setGeometry(QtCore.QRect(1120, 190, 81, 23))
        self.Re_EU_LIST.setObjectName("Re_EU_LIST")
        self.Re_NA_LIST = QtWidgets.QPushButton(self.centralwidget)
        self.Re_NA_LIST.setGeometry(QtCore.QRect(1210, 190, 81, 23))
        self.Re_NA_LIST.setObjectName("Re_NA_LIST")
        self.Re_AP_RULE = QtWidgets.QPushButton(self.centralwidget)
        self.Re_AP_RULE.setGeometry(QtCore.QRect(1030, 250, 81, 23))
        self.Re_AP_RULE.setObjectName("Re_AP_RULE")
        self.Re_EU_RULE = QtWidgets.QPushButton(self.centralwidget)
        self.Re_EU_RULE.setGeometry(QtCore.QRect(1120, 250, 81, 23))
        self.Re_EU_RULE.setObjectName("Re_EU_RULE")
        self.Re_NA_RULE = QtWidgets.QPushButton(self.centralwidget)
        self.Re_NA_RULE.setGeometry(QtCore.QRect(1210, 250, 81, 23))
        self.Re_NA_RULE.setObjectName("Re_NA_RULE")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(1030, 290, 101, 16))
        self.label_32.setObjectName("label_32")
        self.Combo_SCENARIO = QtWidgets.QComboBox(self.centralwidget)
        self.Combo_SCENARIO.setGeometry(QtCore.QRect(1130, 320, 201, 21))
        self.Combo_SCENARIO.setObjectName("Combo_SCENARIO")
        self.Provisoned = QtWidgets.QPushButton(self.centralwidget)
        self.Provisoned.setGeometry(QtCore.QRect(1030, 350, 81, 23))
        self.Provisoned.setObjectName("Provisoned")
        self.POLICY = QtWidgets.QLineEdit(self.centralwidget)
        self.POLICY.setGeometry(QtCore.QRect(1130, 350, 201, 21))
        self.POLICY.setObjectName("POLICY")
        self.New_Election = QtWidgets.QPushButton(self.centralwidget)
        self.New_Election.setGeometry(QtCore.QRect(1030, 320, 81, 23))
        self.New_Election.setObjectName("New_Election")
        self.OWNER = QtWidgets.QComboBox(self.centralwidget)
        self.OWNER.setGeometry(QtCore.QRect(1030, 90, 181, 21))
        self.OWNER.setObjectName("OWNER")
        self.LIST_ROUTE = QtWidgets.QPushButton(self.centralwidget)
        self.LIST_ROUTE.setGeometry(QtCore.QRect(1030, 60, 181, 23))
        self.LIST_ROUTE.setObjectName("LIST_ROUTE")
        self.ROUTE_STATUS = QtWidgets.QComboBox(self.centralwidget)
        self.ROUTE_STATUS.setGeometry(QtCore.QRect(1220, 90, 91, 21))
        self.ROUTE_STATUS.setObjectName("ROUTE_STATUS")
        self.ROUTE_LIST = QtWidgets.QComboBox(self.centralwidget)
        self.ROUTE_LIST.setGeometry(QtCore.QRect(110, 80, 901, 21))
        self.ROUTE_LIST.setMaxVisibleItems(30)
        self.ROUTE_LIST.setObjectName("ROUTE_LIST")
        self.HIDE_LIST_ROUTE = QtWidgets.QPushButton(self.centralwidget)
        self.HIDE_LIST_ROUTE.setGeometry(QtCore.QRect(1220, 60, 91, 23))
        self.HIDE_LIST_ROUTE.setObjectName("HIDE_LIST_ROUTE")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(1030, 160, 91, 20))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(1030, 220, 91, 20))
        self.label_36.setObjectName("label_36")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(1040, 470, 101, 16))
        self.label_33.setObjectName("label_33")
        self.Button_FTRUB = QtWidgets.QPushButton(self.centralwidget)
        self.Button_FTRUB.setGeometry(QtCore.QRect(1030, 490, 211, 23))
        self.Button_FTRUB.setObjectName("Button_FTRUB")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(1020, 40, 301, 111))
        self.widget.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.widget.setObjectName("widget")
        self.label_37 = QtWidgets.QLabel(self.widget)
        self.label_37.setGeometry(QtCore.QRect(20, 0, 91, 20))
        self.label_37.setObjectName("label_37")
        self.CALL_RMT = QtWidgets.QPushButton(self.widget)
        self.CALL_RMT.setGeometry(QtCore.QRect(10, 80, 181, 23))
        self.CALL_RMT.setObjectName("CALL_RMT")
        self.IMSI_A = QtWidgets.QComboBox(self.centralwidget)
        self.IMSI_A.setGeometry(QtCore.QRect(110, 20, 171, 21))
        self.IMSI_A.setStyleSheet("")
        self.IMSI_A.setEditable(True)
        self.IMSI_A.setObjectName("IMSI_A")
        self.IMSI_B = QtWidgets.QComboBox(self.centralwidget)
        self.IMSI_B.setGeometry(QtCore.QRect(620, 20, 171, 21))
        self.IMSI_B.setEditable(True)
        self.IMSI_B.setObjectName("IMSI_B")
        self.TADIG_A = QtWidgets.QComboBox(self.centralwidget)
        self.TADIG_A.setGeometry(QtCore.QRect(340, 20, 161, 21))
        self.TADIG_A.setEditable(True)
        self.TADIG_A.setObjectName("TADIG_A")
        self.TADIG_B = QtWidgets.QComboBox(self.centralwidget)
        self.TADIG_B.setGeometry(QtCore.QRect(860, 20, 151, 21))
        self.TADIG_B.setEditable(True)
        self.TADIG_B.setObjectName("TADIG_B")
        self.SEND_PEER_NOTIFICATION = QtWidgets.QPushButton(self.centralwidget)
        self.SEND_PEER_NOTIFICATION.setGeometry(QtCore.QRect(1030, 410, 101, 23))
        self.SEND_PEER_NOTIFICATION.setObjectName("SEND_PEER_NOTIFICATION")
        self.OWNER_PEER = QtWidgets.QComboBox(self.centralwidget)
        self.OWNER_PEER.setGeometry(QtCore.QRect(1200, 410, 131, 21))
        self.OWNER_PEER.setObjectName("OWNER_PEER")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(1140, 410, 51, 22))
        self.spinBox.setObjectName("spinBox")
        self.Button_K2R = QtWidgets.QPushButton(self.centralwidget)
        self.Button_K2R.setGeometry(QtCore.QRect(1030, 520, 211, 23))
        self.Button_K2R.setObjectName("Button_K2R")
        self.Button_One_Key_Bilateral = QtWidgets.QPushButton(self.centralwidget)
        self.Button_One_Key_Bilateral.setGeometry(QtCore.QRect(1030, 570, 211, 23))
        self.Button_One_Key_Bilateral.setObjectName("Button_One_Key_Bilateral")
        self.widget.raise_()
        self.label.raise_()
        self.SSID_A.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.OP_A.raise_()
        self.Combo_Select_A.raise_()
        self.label_4.raise_()
        self.Country_A.raise_()
        self.label_5.raise_()
        self.realm_A.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.LISTREGION_A.raise_()
        self.label_8.raise_()
        self.LIST_A.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.RMT_A.raise_()
        self.Owner_A.raise_()
        self.label_11.raise_()
        self.DRA_A.raise_()
        self.label_12.raise_()
        self.HUB_POLICY_A.raise_()
        self.label_13.raise_()
        self.TECH_COMMENT_A.raise_()
        self.label_14.raise_()
        self.Combo_Region_A.raise_()
        self.B_Reams2A_LIST.raise_()
        self.Check_TO_A_Route.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.realm_B.raise_()
        self.label_19.raise_()
        self.Country_B.raise_()
        self.LISTREGION_B.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.Combo_Region_B.raise_()
        self.Check_TO_B_Route.raise_()
        self.SSID_B.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.A_Reams2B_LIST.raise_()
        self.DRA_B.raise_()
        self.Combo_Select_B.raise_()
        self.Owner_B.raise_()
        self.LIST_B.raise_()
        self.label_27.raise_()
        self.RMT_B.raise_()
        self.OP_B.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.HUB_POLICY_B.raise_()
        self.TECH_COMMENT_B.raise_()
        self.label_30.raise_()
        self.UPD_DB.raise_()
        self.BKP_DB.raise_()
        self.RST_DB.raise_()
        self.Re_AP_LIST.raise_()
        self.Re_EU_LIST.raise_()
        self.Re_NA_LIST.raise_()
        self.Re_AP_RULE.raise_()
        self.Re_EU_RULE.raise_()
        self.Re_NA_RULE.raise_()
        self.label_32.raise_()
        self.Combo_SCENARIO.raise_()
        self.Provisoned.raise_()
        self.POLICY.raise_()
        self.New_Election.raise_()
        self.OWNER.raise_()
        self.LIST_ROUTE.raise_()
        self.ROUTE_STATUS.raise_()
        self.ROUTE_LIST.raise_()
        self.HIDE_LIST_ROUTE.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_33.raise_()
        self.Button_FTRUB.raise_()
        self.IMSI_A.raise_()
        self.IMSI_B.raise_()
        self.TADIG_A.raise_()
        self.TADIG_B.raise_()
        self.SEND_PEER_NOTIFICATION.raise_()
        self.OWNER_PEER.raise_()
        self.spinBox.raise_()
        self.Button_K2R.raise_()
        self.Button_One_Key_Bilateral.raise_()
        Ui_OPEN_ROUTE_WIN.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_OPEN_ROUTE_WIN)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1352, 21))
        self.menubar.setObjectName("menubar")
        Ui_OPEN_ROUTE_WIN.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_OPEN_ROUTE_WIN)
        self.statusbar.setObjectName("statusbar")
        Ui_OPEN_ROUTE_WIN.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_OPEN_ROUTE_WIN)
        QtCore.QMetaObject.connectSlotsByName(Ui_OPEN_ROUTE_WIN)

    def retranslateUi(self, Ui_OPEN_ROUTE_WIN):
        _translate = QtCore.QCoreApplication.translate
        Ui_OPEN_ROUTE_WIN.setWindowTitle(_translate("Ui_OPEN_ROUTE_WIN", "MainWindow"))
        self.label.setText(_translate("Ui_OPEN_ROUTE_WIN", "SSID_A"))
        self.label_2.setText(_translate("Ui_OPEN_ROUTE_WIN", "TADIG_A"))
        self.label_3.setText(_translate("Ui_OPEN_ROUTE_WIN", "OP_A"))
        self.label_4.setText(_translate("Ui_OPEN_ROUTE_WIN", "Country_A"))
        self.label_5.setText(_translate("Ui_OPEN_ROUTE_WIN", "Realm_A"))
        self.label_6.setText(_translate("Ui_OPEN_ROUTE_WIN", "IMSI_A"))
        self.label_7.setText(_translate("Ui_OPEN_ROUTE_WIN", "LISTREGION_A"))
        self.label_8.setText(_translate("Ui_OPEN_ROUTE_WIN", "LIST_A"))
        self.label_9.setText(_translate("Ui_OPEN_ROUTE_WIN", "Owner_A"))
        self.label_10.setText(_translate("Ui_OPEN_ROUTE_WIN", "RMT_A"))
        self.label_11.setText(_translate("Ui_OPEN_ROUTE_WIN", "DRA_A"))
        self.label_12.setText(_translate("Ui_OPEN_ROUTE_WIN", "HUB_A"))
        self.label_13.setText(_translate("Ui_OPEN_ROUTE_WIN", "TECH_COMMNET_A"))
        self.label_14.setText(_translate("Ui_OPEN_ROUTE_WIN", "Normal Route"))
        self.B_Reams2A_LIST.setText(_translate("Ui_OPEN_ROUTE_WIN", "B_Realms2A_LIST"))
        self.Check_TO_A_Route.setText(_translate("Ui_OPEN_ROUTE_WIN", "Check to A Route"))
        self.label_16.setText(_translate("Ui_OPEN_ROUTE_WIN", "LIST_B"))
        self.label_17.setText(_translate("Ui_OPEN_ROUTE_WIN", "Owner_B"))
        self.label_18.setText(_translate("Ui_OPEN_ROUTE_WIN", "Normal Route"))
        self.label_19.setText(_translate("Ui_OPEN_ROUTE_WIN", "TADIG_B"))
        self.label_20.setText(_translate("Ui_OPEN_ROUTE_WIN", "HUB_B"))
        self.label_21.setText(_translate("Ui_OPEN_ROUTE_WIN", "Country_B"))
        self.label_22.setText(_translate("Ui_OPEN_ROUTE_WIN", "Realm_B"))
        self.label_23.setText(_translate("Ui_OPEN_ROUTE_WIN", "IMSI_B"))
        self.Check_TO_B_Route.setText(_translate("Ui_OPEN_ROUTE_WIN", "Check to B Route"))
        self.label_25.setText(_translate("Ui_OPEN_ROUTE_WIN", "OP_B"))
        self.label_26.setText(_translate("Ui_OPEN_ROUTE_WIN", "LISTREGION_B"))
        self.A_Reams2B_LIST.setText(_translate("Ui_OPEN_ROUTE_WIN", "A_Realms2B_LIST"))
        self.label_27.setText(_translate("Ui_OPEN_ROUTE_WIN", "SSID_B"))
        self.label_28.setText(_translate("Ui_OPEN_ROUTE_WIN", "DRA_B"))
        self.label_29.setText(_translate("Ui_OPEN_ROUTE_WIN", "TECH_COMMNET_B"))
        self.label_30.setText(_translate("Ui_OPEN_ROUTE_WIN", "RMT_A"))
        self.UPD_DB.setText(_translate("Ui_OPEN_ROUTE_WIN", "UPD_DB"))
        self.BKP_DB.setText(_translate("Ui_OPEN_ROUTE_WIN", "Backup_DB"))
        self.RST_DB.setText(_translate("Ui_OPEN_ROUTE_WIN", "Restore_DB"))
        self.Re_AP_LIST.setText(_translate("Ui_OPEN_ROUTE_WIN", "Re_AP_LIST"))
        self.Re_EU_LIST.setText(_translate("Ui_OPEN_ROUTE_WIN", "Re_EU_LIST"))
        self.Re_NA_LIST.setText(_translate("Ui_OPEN_ROUTE_WIN", "Re_NA_LIST"))
        self.Re_AP_RULE.setText(_translate("Ui_OPEN_ROUTE_WIN", "Re_AP_RULE"))
        self.Re_EU_RULE.setText(_translate("Ui_OPEN_ROUTE_WIN", "Re_EU_RULE"))
        self.Re_NA_RULE.setText(_translate("Ui_OPEN_ROUTE_WIN", "Re_NA_RULE"))
        self.label_32.setText(_translate("Ui_OPEN_ROUTE_WIN", "Send Email to Peer"))
        self.Provisoned.setText(_translate("Ui_OPEN_ROUTE_WIN", "Provisioned"))
        self.POLICY.setText(_translate("Ui_OPEN_ROUTE_WIN", "POLICY"))
        self.New_Election.setText(_translate("Ui_OPEN_ROUTE_WIN", "New_Election"))
        self.LIST_ROUTE.setText(_translate("Ui_OPEN_ROUTE_WIN", " On/Refresh"))
        self.HIDE_LIST_ROUTE.setText(_translate("Ui_OPEN_ROUTE_WIN", " Off"))
        self.label_35.setText(_translate("Ui_OPEN_ROUTE_WIN", "Reload ListCache"))
        self.label_36.setText(_translate("Ui_OPEN_ROUTE_WIN", "Reload RuleEngine"))
        self.label_33.setText(_translate("Ui_OPEN_ROUTE_WIN", "Other function"))
        self.Button_FTRUB.setText(_translate("Ui_OPEN_ROUTE_WIN", "One Key FTRUB Route Provison"))
        self.label_37.setText(_translate("Ui_OPEN_ROUTE_WIN", "Route Filter"))
        self.CALL_RMT.setText(_translate("Ui_OPEN_ROUTE_WIN", "call RMT"))
        self.SEND_PEER_NOTIFICATION.setText(_translate("Ui_OPEN_ROUTE_WIN", "Notify Peer(Mon)"))
        self.Button_K2R.setText(_translate("Ui_OPEN_ROUTE_WIN", "One Key K2R route Provison"))
        self.Button_One_Key_Bilateral.setText(_translate("Ui_OPEN_ROUTE_WIN", "One Key Comfone Bilateral Route"))

