# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_OP_ONLINE.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Ui_OP_ONLINE(object):
    def setupUi(self, Ui_OP_ONLINE):
        Ui_OP_ONLINE.setObjectName("Ui_OP_ONLINE")
        Ui_OP_ONLINE.resize(1352, 696)
        self.centralwidget = QtWidgets.QWidget(Ui_OP_ONLINE)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 531, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 531, 16))
        self.label_2.setObjectName("label_2")
        self.sync = QtWidgets.QPushButton(self.centralwidget)
        self.sync.setGeometry(QtCore.QRect(50, 40, 75, 23))
        self.sync.setObjectName("sync")
        self.btn_direct = QtWidgets.QRadioButton(self.centralwidget)
        self.btn_direct.setGeometry(QtCore.QRect(50, 90, 82, 17))
        self.btn_direct.setObjectName("btn_direct")
        self.btn_indirect = QtWidgets.QRadioButton(self.centralwidget)
        self.btn_indirect.setGeometry(QtCore.QRect(150, 90, 82, 17))
        self.btn_indirect.setObjectName("btn_indirect")
        self.SSID = QtWidgets.QLineEdit(self.centralwidget)
        self.SSID.setGeometry(QtCore.QRect(540, 40, 113, 20))
        self.SSID.setObjectName("SSID")
        self.OPERATOR = QtWidgets.QLineEdit(self.centralwidget)
        self.OPERATOR.setGeometry(QtCore.QRect(200, 40, 331, 20))
        self.OPERATOR.setText("")
        self.OPERATOR.setObjectName("OPERATOR")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 190, 101, 16))
        self.label_4.setObjectName("label_4")
        self.LISTNAME = QtWidgets.QLineEdit(self.centralwidget)
        self.LISTNAME.setGeometry(QtCore.QRect(210, 190, 451, 20))
        self.LISTNAME.setText("")
        self.LISTNAME.setObjectName("LISTNAME")
        self.Exisisting_LISTNAME = QtWidgets.QLineEdit(self.centralwidget)
        self.Exisisting_LISTNAME.setGeometry(QtCore.QRect(210, 210, 451, 20))
        self.Exisisting_LISTNAME.setText("")
        self.Exisisting_LISTNAME.setObjectName("Exisisting_LISTNAME")
        self.VIRTUAL_REALM = QtWidgets.QLineEdit(self.centralwidget)
        self.VIRTUAL_REALM.setGeometry(QtCore.QRect(390, 90, 271, 20))
        self.VIRTUAL_REALM.setStyleSheet("color: rgb(255, 85, 255);")
        self.VIRTUAL_REALM.setObjectName("VIRTUAL_REALM")
        self.Lable_VIRTUAL_REALM = QtWidgets.QLabel(self.centralwidget)
        self.Lable_VIRTUAL_REALM.setGeometry(QtCore.QRect(260, 90, 101, 20))
        self.Lable_VIRTUAL_REALM.setObjectName("Lable_VIRTUAL_REALM")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 230, 161, 16))
        self.label_6.setObjectName("label_6")
        self.R2OP_NAME = QtWidgets.QLineEdit(self.centralwidget)
        self.R2OP_NAME.setGeometry(QtCore.QRect(210, 230, 451, 20))
        self.R2OP_NAME.setText("")
        self.R2OP_NAME.setObjectName("R2OP_NAME")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 140, 91, 16))
        self.label_7.setObjectName("label_7")
        self.Local_DSC_AP = QtWidgets.QCheckBox(self.centralwidget)
        self.Local_DSC_AP.setGeometry(QtCore.QRect(130, 140, 70, 17))
        self.Local_DSC_AP.setObjectName("Local_DSC_AP")
        self.Local_DSC_EU = QtWidgets.QCheckBox(self.centralwidget)
        self.Local_DSC_EU.setGeometry(QtCore.QRect(200, 140, 70, 17))
        self.Local_DSC_EU.setObjectName("Local_DSC_EU")
        self.Local_DSC_NA = QtWidgets.QCheckBox(self.centralwidget)
        self.Local_DSC_NA.setGeometry(QtCore.QRect(270, 140, 70, 17))
        self.Local_DSC_NA.setObjectName("Local_DSC_NA")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 280, 531, 16))
        self.label_8.setObjectName("label_8")
        self.DRACustomerRealmName = QtWidgets.QLineEdit(self.centralwidget)
        self.DRACustomerRealmName.setGeometry(QtCore.QRect(50, 300, 611, 20))
        self.DRACustomerRealmName.setText("")
        self.DRACustomerRealmName.setObjectName("DRACustomerRealmName")
        self.DRACustomerNodeName = QtWidgets.QLineEdit(self.centralwidget)
        self.DRACustomerNodeName.setGeometry(QtCore.QRect(50, 350, 611, 20))
        self.DRACustomerNodeName.setText("")
        self.DRACustomerNodeName.setObjectName("DRACustomerNodeName")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 330, 531, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(50, 380, 601, 16))
        self.label_10.setObjectName("label_10")
        self.DRACustomerRealmNameBeforeTranslation = QtWidgets.QLineEdit(self.centralwidget)
        self.DRACustomerRealmNameBeforeTranslation.setGeometry(QtCore.QRect(50, 400, 611, 20))
        self.DRACustomerRealmNameBeforeTranslation.setText("")
        self.DRACustomerRealmNameBeforeTranslation.setObjectName("DRACustomerRealmNameBeforeTranslation")
        self.IMSI = QtWidgets.QLineEdit(self.centralwidget)
        self.IMSI.setGeometry(QtCore.QRect(50, 450, 611, 20))
        self.IMSI.setText("")
        self.IMSI.setObjectName("IMSI")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(50, 430, 601, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(50, 480, 621, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(50, 510, 621, 16))
        self.label_13.setObjectName("label_13")
        self.Combo_LIST_REGION = QtWidgets.QComboBox(self.centralwidget)
        self.Combo_LIST_REGION.setGeometry(QtCore.QRect(50, 530, 111, 22))
        self.Combo_LIST_REGION.setObjectName("Combo_LIST_REGION")
        self.ADD_TEST_ENTRY = QtWidgets.QPushButton(self.centralwidget)
        self.ADD_TEST_ENTRY.setGeometry(QtCore.QRect(170, 530, 171, 23))
        self.ADD_TEST_ENTRY.setObjectName("ADD_TEST_ENTRY")
        self.RELOADLIST = QtWidgets.QPushButton(self.centralwidget)
        self.RELOADLIST.setGeometry(QtCore.QRect(360, 530, 171, 23))
        self.RELOADLIST.setObjectName("RELOADLIST")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(50, 560, 621, 16))
        self.label_14.setObjectName("label_14")
        self.C_RequestFilter = QtWidgets.QPushButton(self.centralwidget)
        self.C_RequestFilter.setGeometry(QtCore.QRect(170, 580, 171, 23))
        self.C_RequestFilter.setObjectName("C_RequestFilter")
        self.C_RequestFilter_reload = QtWidgets.QPushButton(self.centralwidget)
        self.C_RequestFilter_reload.setGeometry(QtCore.QRect(360, 580, 171, 23))
        self.C_RequestFilter_reload.setObjectName("C_RequestFilter_reload")
        self.Combo_RF_REGION = QtWidgets.QComboBox(self.centralwidget)
        self.Combo_RF_REGION.setGeometry(QtCore.QRect(50, 580, 111, 22))
        self.Combo_RF_REGION.setObjectName("Combo_RF_REGION")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(700, 20, 621, 16))
        self.label_15.setObjectName("label_15")
        self.Combo_DR_REGION = QtWidgets.QComboBox(self.centralwidget)
        self.Combo_DR_REGION.setGeometry(QtCore.QRect(700, 40, 81, 22))
        self.Combo_DR_REGION.setObjectName("Combo_DR_REGION")
        self.Combo_DR_TYPE = QtWidgets.QComboBox(self.centralwidget)
        self.Combo_DR_TYPE.setGeometry(QtCore.QRect(790, 40, 141, 22))
        self.Combo_DR_TYPE.setObjectName("Combo_DR_TYPE")
        self.C_Route = QtWidgets.QPushButton(self.centralwidget)
        self.C_Route.setGeometry(QtCore.QRect(950, 40, 101, 23))
        self.C_Route.setObjectName("C_Route")
        self.RELOAD_DECIDE_ROUTE_ON_REGION = QtWidgets.QPushButton(self.centralwidget)
        self.RELOAD_DECIDE_ROUTE_ON_REGION.setGeometry(QtCore.QRect(1070, 40, 201, 23))
        self.RELOAD_DECIDE_ROUTE_ON_REGION.setObjectName("RELOAD_DECIDE_ROUTE_ON_REGION")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(700, 100, 41, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(700, 150, 41, 16))
        self.label_17.setObjectName("label_17")
        self.CONDITION = QtWidgets.QTextEdit(self.centralwidget)
        self.CONDITION.setGeometry(QtCore.QRect(790, 100, 531, 41))
        self.CONDITION.setObjectName("CONDITION")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(700, 70, 41, 16))
        self.label_18.setObjectName("label_18")
        self.PRIORITY = QtWidgets.QLineEdit(self.centralwidget)
        self.PRIORITY.setGeometry(QtCore.QRect(790, 70, 171, 20))
        self.PRIORITY.setText("")
        self.PRIORITY.setObjectName("PRIORITY")
        self.CONSEQUENCE = QtWidgets.QTextEdit(self.centralwidget)
        self.CONSEQUENCE.setGeometry(QtCore.QRect(790, 150, 531, 41))
        self.CONSEQUENCE.setObjectName("CONSEQUENCE")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(700, 200, 621, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(700, 220, 621, 16))
        self.label_20.setObjectName("label_20")
        self.IMSI2REALM = QtWidgets.QPushButton(self.centralwidget)
        self.IMSI2REALM.setGeometry(QtCore.QRect(700, 240, 171, 23))
        self.IMSI2REALM.setObjectName("IMSI2REALM")
        self.IMSI_TO_K2RREALM = QtWidgets.QPushButton(self.centralwidget)
        self.IMSI_TO_K2RREALM.setGeometry(QtCore.QRect(890, 240, 171, 23))
        self.IMSI_TO_K2RREALM.setObjectName("IMSI_TO_K2RREALM")
        self.RELOADMAP = QtWidgets.QPushButton(self.centralwidget)
        self.RELOADMAP.setGeometry(QtCore.QRect(1080, 240, 171, 23))
        self.RELOADMAP.setObjectName("RELOADMAP")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(50, 610, 621, 16))
        self.label_21.setObjectName("label_21")
        self.ADDREAL2OP = QtWidgets.QPushButton(self.centralwidget)
        self.ADDREAL2OP.setGeometry(QtCore.QRect(50, 630, 111, 23))
        self.ADDREAL2OP.setObjectName("ADDREAL2OP")
        self.RELOADREALM2OP = QtWidgets.QPushButton(self.centralwidget)
        self.RELOADREALM2OP.setGeometry(QtCore.QRect(170, 630, 171, 23))
        self.RELOADREALM2OP.setObjectName("RELOADREALM2OP")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(700, 270, 621, 16))
        self.label_22.setObjectName("label_22")
        self.EMAIL = QtWidgets.QPushButton(self.centralwidget)
        self.EMAIL.setGeometry(QtCore.QRect(700, 290, 171, 23))
        self.EMAIL.setObjectName("EMAIL")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(700, 320, 41, 16))
        self.label_23.setObjectName("label_23")
        self.LOG = QtWidgets.QTextEdit(self.centralwidget)
        self.LOG.setGeometry(QtCore.QRect(690, 340, 641, 311))
        self.LOG.setObjectName("LOG")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 170, 531, 16))
        self.label_5.setObjectName("label_5")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(140, 40, 51, 16))
        self.label_24.setObjectName("label_24")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 531, 16))
        self.label_3.setObjectName("label_3")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(50, 210, 101, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(50, 260, 531, 16))
        self.label_26.setObjectName("label_26")
        Ui_OP_ONLINE.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_OP_ONLINE)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1352, 21))
        self.menubar.setObjectName("menubar")
        Ui_OP_ONLINE.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_OP_ONLINE)
        self.statusbar.setObjectName("statusbar")
        Ui_OP_ONLINE.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_OP_ONLINE)
        QtCore.QMetaObject.connectSlotsByName(Ui_OP_ONLINE)

    def retranslateUi(self, Ui_OP_ONLINE):
        _translate = QtCore.QCoreApplication.translate
        Ui_OP_ONLINE.setWindowTitle(_translate("Ui_OP_ONLINE", "MainWindow"))
        self.label.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">1.*Provision CCB common attributes.   *Click UPD DB in Open route.   *Select OP_A in Open Route *Click Sync.</span></p></body></html>"))
        self.label_2.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">2.*Select In/Direct.        *If Direct,input Virtual ReamName on Local DSC.</span></p><p><br/></p></body></html>"))
        self.sync.setText(_translate("Ui_OP_ONLINE", "Sync"))
        self.btn_direct.setText(_translate("Ui_OP_ONLINE", "Direct OP"))
        self.btn_indirect.setText(_translate("Ui_OP_ONLINE", "InDirect OP"))
        self.SSID.setText(_translate("Ui_OP_ONLINE", "SSID"))
        self.label_4.setText(_translate("Ui_OP_ONLINE", "Proposed LIST Name:"))
        self.VIRTUAL_REALM.setText(_translate("Ui_OP_ONLINE", "Change Me!"))
        self.Lable_VIRTUAL_REALM.setText(_translate("Ui_OP_ONLINE", "Virtual Realm name:"))
        self.label_6.setText(_translate("Ui_OP_ONLINE", "Proposed Realm2OP Name:"))
        self.label_7.setText(_translate("Ui_OP_ONLINE", "Local DSC:"))
        self.Local_DSC_AP.setText(_translate("Ui_OP_ONLINE", "AP DSC"))
        self.Local_DSC_EU.setText(_translate("Ui_OP_ONLINE", "EU DSC"))
        self.Local_DSC_NA.setText(_translate("Ui_OP_ONLINE", "NA DSC"))
        self.label_8.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">DRACustomerRealmName:Public Realms used by customer\'s RP to route s6a messages to the customer</span></p></body></html>"))
        self.label_9.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">DRACustomerNodeRealm:Customer peer realm name in Peer display_name which is different with DRACustomerRealmName</span></p></body></html>"))
        self.label_10.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">DRACustomerRealmNameBeforeTranslation:Private Realms used by customer\'s node route s6a messages to the customer</span></p></body></html>"))
        self.label_11.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">IMSI prefix #used in MAP_IMSI2REALM &amp; MAP_IMSI2K2RREALM</span></p></body></html>"))
        self.label_12.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">6.On local DSCs,manually create Cacheable=True,PLAIN_LIST Listcache with the name finalized in Proposed LIST Name.</span></p></body></html>"))
        self.label_13.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">7.On local DSCs, add test entry to verify and aviod alarm then reload listcache.</span></p><p><br/></p></body></html>"))
        self.ADD_TEST_ENTRY.setText(_translate("Ui_OP_ONLINE", "Add test entry in LIST(local DSC)"))
        self.RELOADLIST.setText(_translate("Ui_OP_ONLINE", "Reload LISTCACHE in the region"))
        self.label_14.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">8.On local DSCs, create Request Filter, linking DRACustomerRealmName &amp; RealmNameBeforeTranslation to LISTCACHE.</span></p></body></html>"))
        self.C_RequestFilter.setText(_translate("Ui_OP_ONLINE", "Create RequestFilter(Local DSC)"))
        self.C_RequestFilter_reload.setText(_translate("Ui_OP_ONLINE", "Reload RuleEngine in the Region"))
        self.label_15.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">10.Create DecideRoute to CustomerRealmName on all region and to CustomerRealmNameBeforeTranslation on local DSC</span></p></body></html>"))
        self.C_Route.setText(_translate("Ui_OP_ONLINE", "Add Decide Route"))
        self.RELOAD_DECIDE_ROUTE_ON_REGION.setText(_translate("Ui_OP_ONLINE", "Reload RuleEngine in the Region"))
        self.label_16.setText(_translate("Ui_OP_ONLINE", "Cond:"))
        self.label_17.setText(_translate("Ui_OP_ONLINE", "Cons:"))
        self.label_18.setText(_translate("Ui_OP_ONLINE", "Priority:"))
        self.label_19.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">11.ADD MAP_IMSI2REALM, ADD MAP_IMSI2K2RREALM on all regions and Reload MAPCACHE on all regions</span></p></body></html>"))
        self.label_20.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">#All IMSI will be mapped according to the first realm of DRACustomerRealmName</span></p></body></html>"))
        self.IMSI2REALM.setText(_translate("Ui_OP_ONLINE", "Add MAP_IMSI2REALM"))
        self.IMSI_TO_K2RREALM.setText(_translate("Ui_OP_ONLINE", "Add MAP_IMSI_TO_K2RREALM"))
        self.RELOADMAP.setText(_translate("Ui_OP_ONLINE", "Reload MAP All"))
        self.label_21.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">9.ADD REALM2OP on all regional DSC and Reload REALM2OP for billing</span></p></body></html>"))
        self.ADDREAL2OP.setText(_translate("Ui_OP_ONLINE", "Add Realm2OP on All"))
        self.RELOADREALM2OP.setText(_translate("Ui_OP_ONLINE", "Reload Realm2OP on All"))
        self.label_22.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">12.Send Email for team leader to review</span></p></body></html>"))
        self.EMAIL.setText(_translate("Ui_OP_ONLINE", "Send Email"))
        self.label_23.setText(_translate("Ui_OP_ONLINE", "LOG:"))
        self.label_5.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">4.ReEdit Proposed LIST name/Realm2OP name if necessary.If there is Existing name, do not create new.</span></p><p><br/></p></body></html>"))
        self.label_24.setText(_translate("Ui_OP_ONLINE", "OP Name:"))
        self.label_3.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">3.Check Local DSC. </span></p><p><br/></p></body></html>"))
        self.label_25.setText(_translate("Ui_OP_ONLINE", "Existing LIST Name:"))
        self.label_26.setText(_translate("Ui_OP_ONLINE", "<html><head/><body><p><span style=\" color:#0000ff;\">5.Double check parameters read from CCB.</span></p><p><br/></p></body></html>"))

