# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_UPD_RMT_ROUTE.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UPD_RMT_ROUTE(object):
    def setupUi(self, UPD_RMT_ROUTE):
        UPD_RMT_ROUTE.setObjectName("UPD_RMT_ROUTE")
        UPD_RMT_ROUTE.resize(1276, 1021)
        UPD_RMT_ROUTE.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.centralwidget = QtWidgets.QWidget(UPD_RMT_ROUTE)
        self.centralwidget.setObjectName("centralwidget")
        self.OP = QtWidgets.QLineEdit(self.centralwidget)
        self.OP.setGeometry(QtCore.QRect(190, 20, 371, 21))
        self.OP.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.OP.setObjectName("OP")
        self.OP_SELECT = QtWidgets.QComboBox(self.centralwidget)
        self.OP_SELECT.setGeometry(QtCore.QRect(190, 50, 371, 21))
        self.OP_SELECT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.OP_SELECT.setObjectName("OP_SELECT")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(70, 190, 1191, 441))
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setRowCount(1000)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(5)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.OP_LIST = QtWidgets.QLineEdit(self.centralwidget)
        self.OP_LIST.setGeometry(QtCore.QRect(190, 80, 371, 21))
        self.OP_LIST.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);")
        self.OP_LIST.setText("")
        self.OP_LIST.setObjectName("OP_LIST")
        self.REGION_SELECT = QtWidgets.QComboBox(self.centralwidget)
        self.REGION_SELECT.setGeometry(QtCore.QRect(70, 640, 101, 21))
        self.REGION_SELECT.setObjectName("REGION_SELECT")
        self.REGION_SELECT.addItem("")
        self.REGION_SELECT.addItem("")
        self.REGION_SELECT.addItem("")
        self.REGION_SELECT.addItem("")
        self.PROVISION = QtWidgets.QPushButton(self.centralwidget)
        self.PROVISION.setGeometry(QtCore.QRect(200, 640, 75, 23))
        self.PROVISION.setObjectName("PROVISION")
        self.EMAIL = QtWidgets.QPushButton(self.centralwidget)
        self.EMAIL.setGeometry(QtCore.QRect(420, 640, 191, 23))
        self.EMAIL.setObjectName("EMAIL")
        self.RELOAD_LIST = QtWidgets.QPushButton(self.centralwidget)
        self.RELOAD_LIST.setGeometry(QtCore.QRect(310, 640, 75, 23))
        self.RELOAD_LIST.setObjectName("RELOAD_LIST")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 50, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 80, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.BUILD = QtWidgets.QPushButton(self.centralwidget)
        self.BUILD.setGeometry(QtCore.QRect(70, 150, 131, 23))
        self.BUILD.setObjectName("BUILD")
        self.LISTREGION = QtWidgets.QLineEdit(self.centralwidget)
        self.LISTREGION.setGeometry(QtCore.QRect(190, 110, 371, 21))
        self.LISTREGION.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LISTREGION.setText("")
        self.LISTREGION.setObjectName("LISTREGION")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 110, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(600, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.HUB_POLICY = QtWidgets.QTextEdit(self.centralwidget)
        self.HUB_POLICY.setGeometry(QtCore.QRect(600, 50, 481, 81))
        self.HUB_POLICY.setAutoFillBackground(True)
        self.HUB_POLICY.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.HUB_POLICY.setObjectName("HUB_POLICY")
        self.INPUT = QtWidgets.QPushButton(self.centralwidget)
        self.INPUT.setGeometry(QtCore.QRect(230, 150, 151, 23))
        self.INPUT.setObjectName("INPUT")
        self.INPUT_EDIT = QtWidgets.QTextEdit(self.centralwidget)
        self.INPUT_EDIT.setGeometry(QtCore.QRect(70, 190, 401, 441))
        self.INPUT_EDIT.setAutoFillBackground(True)
        self.INPUT_EDIT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.INPUT_EDIT.setObjectName("INPUT_EDIT")
        self.LOG = QtWidgets.QTextEdit(self.centralwidget)
        self.LOG.setGeometry(QtCore.QRect(570, 190, 671, 441))
        self.LOG.setAutoFillBackground(True)
        self.LOG.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LOG.setObjectName("LOG")
        self.EMAIL_2 = QtWidgets.QPushButton(self.centralwidget)
        self.EMAIL_2.setGeometry(QtCore.QRect(630, 640, 91, 23))
        self.EMAIL_2.setObjectName("EMAIL_2")
        self.LOG.raise_()
        self.INPUT_EDIT.raise_()
        self.OP_SELECT.raise_()
        self.OP.raise_()
        self.tableWidget.raise_()
        self.OP_LIST.raise_()
        self.REGION_SELECT.raise_()
        self.PROVISION.raise_()
        self.EMAIL.raise_()
        self.RELOAD_LIST.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.BUILD.raise_()
        self.LISTREGION.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.HUB_POLICY.raise_()
        self.INPUT.raise_()
        self.EMAIL_2.raise_()
        UPD_RMT_ROUTE.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UPD_RMT_ROUTE)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1276, 21))
        self.menubar.setObjectName("menubar")
        UPD_RMT_ROUTE.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UPD_RMT_ROUTE)
        self.statusbar.setObjectName("statusbar")
        UPD_RMT_ROUTE.setStatusBar(self.statusbar)

        self.retranslateUi(UPD_RMT_ROUTE)
        QtCore.QMetaObject.connectSlotsByName(UPD_RMT_ROUTE)

    def retranslateUi(self, UPD_RMT_ROUTE):
        _translate = QtCore.QCoreApplication.translate
        UPD_RMT_ROUTE.setWindowTitle(_translate("UPD_RMT_ROUTE", "MainWindow"))
        UPD_RMT_ROUTE.setToolTip(_translate("UPD_RMT_ROUTE", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("UPD_RMT_ROUTE", "M"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("UPD_RMT_ROUTE", "Roaming Partner"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("UPD_RMT_ROUTE", "M"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("UPD_RMT_ROUTE", "info"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("UPD_RMT_ROUTE", "RP Realms"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("UPD_RMT_ROUTE", "Region"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("UPD_RMT_ROUTE", "Result"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("UPD_RMT_ROUTE", "Result"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.REGION_SELECT.setItemText(0, _translate("UPD_RMT_ROUTE", "Please Select"))
        self.REGION_SELECT.setItemText(1, _translate("UPD_RMT_ROUTE", "AP"))
        self.REGION_SELECT.setItemText(2, _translate("UPD_RMT_ROUTE", "EU"))
        self.REGION_SELECT.setItemText(3, _translate("UPD_RMT_ROUTE", "NA"))
        self.PROVISION.setText(_translate("UPD_RMT_ROUTE", "Provision"))
        self.EMAIL.setText(_translate("UPD_RMT_ROUTE", "Email(Only after provison)"))
        self.RELOAD_LIST.setText(_translate("UPD_RMT_ROUTE", "Reload_LIST"))
        self.label.setText(_translate("UPD_RMT_ROUTE", "Input OP Name"))
        self.label_2.setText(_translate("UPD_RMT_ROUTE", "Select OP"))
        self.label_3.setText(_translate("UPD_RMT_ROUTE", "LISTCACHE of OP"))
        self.BUILD.setText(_translate("UPD_RMT_ROUTE", "Build Table from RMT"))
        self.label_4.setText(_translate("UPD_RMT_ROUTE", "LISTCACHE Region"))
        self.label_5.setText(_translate("UPD_RMT_ROUTE", "Hub Policy"))
        self.HUB_POLICY.setHtml(_translate("UPD_RMT_ROUTE", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.INPUT.setText(_translate("UPD_RMT_ROUTE", "Input entry to add to list"))
        self.INPUT_EDIT.setHtml(_translate("UPD_RMT_ROUTE", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.LOG.setHtml(_translate("UPD_RMT_ROUTE", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.EMAIL_2.setText(_translate("UPD_RMT_ROUTE", "Email 2"))

