# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windtest.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UPDATE_RMT_ROUTE(object):
    def setupUi(self, WindTestMainWin):
        WindTestMainWin.setObjectName("WindTestMainWin")
        WindTestMainWin.resize(1076, 896)
        self.centralwidget = QtWidgets.QWidget(WindTestMainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(70, 20, 611, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(80, 30, 500, 500))
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 500))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 5000, 5000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(5000, 5000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(151, 131, 228, 290))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_wind1_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind1_3.setObjectName("pushButton_wind1_3")
        self.verticalLayout_5.addWidget(self.pushButton_wind1_3)
        self.pushButton_wind2_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind2_3.setObjectName("pushButton_wind2_3")
        self.verticalLayout_5.addWidget(self.pushButton_wind2_3)
        self.pushButton_wind3_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind3_3.setObjectName("pushButton_wind3_3")
        self.verticalLayout_5.addWidget(self.pushButton_wind3_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_wind2_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind2_4.setObjectName("pushButton_wind2_4")
        self.verticalLayout_6.addWidget(self.pushButton_wind2_4)
        self.pushButton_wind1_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind1_4.setObjectName("pushButton_wind1_4")
        self.verticalLayout_6.addWidget(self.pushButton_wind1_4)
        self.pushButton_wind3_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind3_4.setObjectName("pushButton_wind3_4")
        self.verticalLayout_6.addWidget(self.pushButton_wind3_4)
        self.pushButton_wind4_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind4_4.setObjectName("pushButton_wind4_4")
        self.verticalLayout_6.addWidget(self.pushButton_wind4_4)
        self.pushButton_wind5_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind5_4.setObjectName("pushButton_wind5_4")
        self.verticalLayout_6.addWidget(self.pushButton_wind5_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.pushButton_wind4_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind4_3.setObjectName("pushButton_wind4_3")
        self.verticalLayout_5.addWidget(self.pushButton_wind4_3)
        self.pushButton_wind5_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind5_3.setObjectName("pushButton_wind5_3")
        self.verticalLayout_5.addWidget(self.pushButton_wind5_3)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 2, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_wind1_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind1_2.setObjectName("pushButton_wind1_2")
        self.verticalLayout_2.addWidget(self.pushButton_wind1_2)
        self.pushButton_wind2_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind2_2.setObjectName("pushButton_wind2_2")
        self.verticalLayout_2.addWidget(self.pushButton_wind2_2)
        self.pushButton_wind3_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind3_2.setObjectName("pushButton_wind3_2")
        self.verticalLayout_2.addWidget(self.pushButton_wind3_2)
        self.pushButton_wind4_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind4_2.setObjectName("pushButton_wind4_2")
        self.verticalLayout_2.addWidget(self.pushButton_wind4_2)
        self.pushButton_wind5_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_wind5_2.setObjectName("pushButton_wind5_2")
        self.verticalLayout_2.addWidget(self.pushButton_wind5_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tabWidget.raise_()
        self.pushButton_wind1_3.raise_()
        WindTestMainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WindTestMainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 21))
        self.menubar.setObjectName("menubar")
        WindTestMainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WindTestMainWin)
        self.statusbar.setObjectName("statusbar")
        WindTestMainWin.setStatusBar(self.statusbar)

        self.retranslateUi(WindTestMainWin)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WindTestMainWin)

    def retranslateUi(self, WindTestMainWin):
        _translate = QtCore.QCoreApplication.translate
        WindTestMainWin.setWindowTitle(_translate("WindTestMainWin", "MainWindow"))
        self.pushButton_wind1_3.setText(_translate("WindTestMainWin", "wind1"))
        self.pushButton_wind2_3.setText(_translate("WindTestMainWin", "wind2"))
        self.pushButton_wind3_3.setText(_translate("WindTestMainWin", "wind3"))
        self.pushButton_wind2_4.setText(_translate("WindTestMainWin", "wind7"))
        self.pushButton_wind1_4.setText(_translate("WindTestMainWin", "wind6"))
        self.pushButton_wind3_4.setText(_translate("WindTestMainWin", "wind8"))
        self.pushButton_wind4_4.setText(_translate("WindTestMainWin", "wind9"))
        self.pushButton_wind5_4.setText(_translate("WindTestMainWin", "wind10"))
        self.pushButton_wind4_3.setText(_translate("WindTestMainWin", "wind4"))
        self.pushButton_wind5_3.setText(_translate("WindTestMainWin", "wind5"))
        self.pushButton_wind1_2.setText(_translate("WindTestMainWin", "wind6"))
        self.pushButton_wind2_2.setText(_translate("WindTestMainWin", "wind7"))
        self.pushButton_wind3_2.setText(_translate("WindTestMainWin", "wind8"))
        self.pushButton_wind4_2.setText(_translate("WindTestMainWin", "wind9"))
        self.pushButton_wind5_2.setText(_translate("WindTestMainWin", "wind10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("WindTestMainWin", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("WindTestMainWin", "Tab 2"))

